# Generated by Django 3.0.8 on 2020-09-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='enter', max_length=100)),
                ('image', models.ImageField(upload_to='country/images')),
            ],
        ),
        migrations.CreateModel(
            name='disaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='enter', max_length=100)),
                ('image', models.ImageField(upload_to='country/images')),
                ('precautions', models.TextField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='safehaven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='enter', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='enter', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lattitude', models.CharField(default='enter', max_length=100)),
                ('Longitude', models.CharField(default='enter', max_length=100)),
                ('severity', models.CharField(max_length=100)),
                ('startdate', models.DateField(null=True)),
                ('enddate', models.DateField(null=True)),
                ('safehaven', models.ManyToManyField(to='country.safehaven')),
                ('transport', models.ManyToManyField(to='country.transport')),
            ],
        ),
    ]
