# Generated by Django 3.0.8 on 2020-09-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='final',
            name='country',
            field=models.ManyToManyField(to='country.countries'),
        ),
    ]
