# Generated by Django 3.0.8 on 2020-10-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaltable',
            name='Lattitude',
            field=models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='Longitude',
            field=models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=19, null=True),
        ),
    ]
