# Generated by Django 3.0.8 on 2020-09-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_final_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='final',
            name='disaster',
            field=models.ManyToManyField(to='country.disaster'),
        ),
    ]
