# Generated by Django 3.0.8 on 2020-10-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_auto_20201002_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaltable',
            name='Lattitude',
            field=models.DecimalField(blank=True, decimal_places=10, default=22.35, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='Longitude',
            field=models.DecimalField(blank=True, decimal_places=10, default=33.55, max_digits=19, null=True),
        ),
    ]
