# Generated by Django 3.0.8 on 2020-10-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_auto_20201002_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finaltable',
            name='Lattitude',
        ),
        migrations.RemoveField(
            model_name='finaltable',
            name='Longitude',
        ),
        migrations.AddField(
            model_name='finaltable',
            name='Lattitud',
            field=models.DecimalField(blank=True, decimal_places=10, default=22.35, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='finaltable',
            name='Longitud',
            field=models.DecimalField(blank=True, decimal_places=10, default=33.55, max_digits=19, null=True),
        ),
    ]
