# Generated by Django 3.0.8 on 2020-10-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_auto_20201002_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaltable',
            name='Lattitud',
            field=models.DecimalField(blank=True, decimal_places=4, default=22.35, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='Longitud',
            field=models.DecimalField(blank=True, decimal_places=4, default=33.55, max_digits=19, null=True),
        ),
    ]
