# Generated by Django 3.0.8 on 2020-10-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_auto_20201002_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaltable',
            name='radius',
            field=models.IntegerField(default=0),
        ),
    ]
