# Generated by Django 3.1 on 2020-10-02 16:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_finaltable_radius'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helpline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(max_length=12)),
                ('country', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='country.countries')),
                ('disaster', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='country.disaster')),
            ],
        ),
        migrations.RemoveField(
            model_name='finaltable',
            name='safehaven',
        ),
        migrations.RemoveField(
            model_name='finaltable',
            name='transport',
        ),
        migrations.AddField(
            model_name='finaltable',
            name='additionInfo',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finaltable',
            name='city',
            field=models.CharField(default='Mumbai', max_length=100),
        ),
        migrations.AddField(
            model_name='finaltable',
            name='endTime',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='finaltable',
            name='startTime',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='safehaven',
        ),
        migrations.DeleteModel(
            name='transport',
        ),
    ]
