# Generated by Django 3.1 on 2020-10-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0007_auto_20201002_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finaltable',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='finaltable',
            name='startTime',
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='enddate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='startdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
