# Generated by Django 3.1 on 2020-10-03 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0010_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpline',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='country.countries'),
        ),
        migrations.AlterField(
            model_name='helpline',
            name='disaster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='country.disaster'),
        ),
    ]
