# Generated by Django 3.2.4 on 2021-10-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_emails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/country'),
        ),
    ]
